---
  - name: Server is rebooting
    shell: "sleep 5 && reboot"
    async: 1
    poll: 0

  - name: Wait for the reboot to complete
    wait_for_connection:
      connect_timeout: 60
      sleep: 5
      delay: 5
      timeout: 600
