---
  - name: Redhat Subscription Online Registration 
    shell: /usr/sbin/subscription-manager unregister --proxy {{ http_proxy }} --proxyuser {{ PROXYUSER }} --proxypassword {{ PROXYPASSWORD }} 
    when: "ansible_distribution == 'RedHat'"
    register: redhat_subscription_registration
