---
  # This collection of tasks creates a empty list and save it as a fact.
  #  For every item that is encountered (without the tag being skipped),
  #  add a string to the list.
  - name: create empty list for unneeded packages
    set_fact:
      unneeded_packages: []

  - name: 2.2.4 - Remove avahi; add to removal list
    set_fact:
      unneeded_packages: "{{ unneeded_packages + [ 'avahi' ] }}"
    tags:
      - 2.2.4

  - name: 2.2.6 - Remove squid; add to removal list
    set_fact:
      unneeded_packages: "{{ unneeded_packages + [ 'squid' ] }}"
    tags:
      - 2.2.6

  - name: 2.2.7 - Remove samba; add to removal list
    set_fact:
      unneeded_packages: "{{ unneeded_packages + [ 'samba' ] }}"
    when: smb_server is defined and not smb_server
    tags:
      - 2.2.7

  - name: 2.2.8 - Remove dovecot; add to removal list
    set_fact:
      unneeded_packages: "{{ unneeded_packages + [ 'dovecot' ] }}"
    when: email_server is defined and not email_server
    tags:
      - 2.2.8

  - name: 2.2.9 - Remove httpd; add to removal list
    set_fact:
      unneeded_packages: "{{ unneeded_packages + [ 'httpd' ] + [ 'httpd-tools' ] + [ 'mod_ssl' ] }}"
    when: http_server is defined and not http_server
    tags:
      - 2.2.9

  - name: 2.2.10 - Remove vsftpd; add to removal list
    set_fact:
      unneeded_packages: "{{ unneeded_packages + [ 'vsftpd' ] }}"
    when: ftp_server is defined and not ftp_server
    tags:
      - 2.2.10

  - name: 2.2.11 - Remove bind; add to removal list
    set_fact:
      unneeded_packages: "{{ unneeded_packages + [ 'bind' ] + [ 'unbound' ] }}"
    when: dns_server is defined and not dns_server
    tags:
      - 2.2.11

  - name: 2.2.12 - Remove nfs server; add to removal list
    set_fact:
      unneeded_packages: "{{ unneeded_packages + [ 'nfs-utils' ] }}"
    when: nfs_server is defined and not nfs_server
    tags:
      - 2.2.12

  - name: 2.2.13 - Remove rpcbind; add to removal list
    set_fact:
      unneeded_packages: "{{ unneeded_packages + [ 'rpcbind' ] }}"
    tags:
      - 2.2.13

  # control 2.2.14 skipped. RHEL uses LDAP implemented in SSSD by default

  - name: 2.2.15 - Disable dhcpd server [controlled by host variable dhcp_server]; add to removal list
    set_fact:
      unneeded_packages: "{{ unneeded_packages + [ 'dhcp' ] }}"
    when: dhcp_server is defined and not dhcp_server
    tags:
      - 2.2.15

  - name: 2.2.17 - Remove ypserv; add to removal list
    set_fact:
      unneeded_packages: "{{ unneeded_packages + [ 'ypserv' ] }}"
    tags:
      - 2.2.17

  - name: 2.3.1 - Remove ypbind; add to removal list
    set_fact:
      unneeded_packages: "{{ unneeded_packages + [ 'ypbind' ] }}"
    tags:
      - 2.3.1

  - name: 2.3.2 - Remove telnet; add to removal list
    set_fact:
      unneeded_packages: "{{ unneeded_packages + [ 'telnet' ] }}"
    tags:
      - 2.3.2

  - name: 2.3.3 - Remove openldap-clients; add to removal list
    set_fact:
      unneeded_packages: "{{ unneeded_packages + [ 'openldap-clients' ] }}"
    tags:
      - 2.3.3

  - name: 2.3.3 - list of packages to remove
    debug:
      var: unneeded_packages

  # With the list complete, use it with the system's package manager
  #  to remove packages from the system that are not needed.
  - name: Process removal list
    dnf:
      name: "{{ unneeded_packages }}"
      state: absent
