---
  - name: 5.4.1 - Configure PAM files and password requirements
    block:
      - name: 5.4.1 - require at least one digit in passwords
        lineinfile:
          path: /etc/security/pwquality.conf
          line: dcredit = -1
          regexp: "^dcredit = -1"
          insertafter: "# dcredit = 0"

      - name: 5.4.1 - require at least one uppercase letter in passwords
        lineinfile:
          path: /etc/security/pwquality.conf
          line: ucredit = -1
          regexp: "^ucredit = -1"
          insertafter: "# ucredit = 0"

      - name: 5.4.1 - require at least one lowercase letter in passwords
        lineinfile:
          path: /etc/security/pwquality.conf
          line: lcredit = -1
          regexp: "^lcredit = -1"
          insertafter: "^# lcredit = 0"

      - name: 5.4.1 - Require at least one special character in passwords
        lineinfile:
          path: /etc/security/pwquality.conf
          line: ocredit = -1
          regexp: "^ocredit = -1"
          insertafter: "^# ocredit = 0"

      - name: 5.4.1 - Require at least {{ password_min_length }} characters in passwords
        lineinfile:
          path: /etc/security/pwquality.conf
          line: minlen = 8
          regexp: "^minlen = 8"
          insertafter: "^# minlen = 8"
    tags:
      - 5.4.1
