---
  - name: 1.6.2 - Ensure address space layout reandomization (ASLR) is enabled
      # The sysctl module will set variables in /etc/sysctl.conf and tell sysctl
      #  to reload them immediately if 'reload' is set to 'yes'.
    sysctl:
      name: kernel.randomize_va_space
      value: "2"
      reload: yes
      state: present
      sysctl_set: yes
    tags:
      - 1.6.2
