---
  - name: 6.1.[2,4] - Ensure permissions on /etc/passwd /etc/group
    file:
      path: /etc/{{ item }}
      owner: root
      group: root
      mode: 0644
    loop:
      - passwd
      - group
    tags:
      - 6.1.2
      - 6.1.4

  - name: 6.1.[3,5] - Ensure permissions on /etc/shadow /etc/gshadow
    file:
      path: /etc/{{ item }}
      owner: root
      group: root
      mode: 0000
    loop:
      - shadow
      - gshadow
    tags:
      - 6.1.3
      - 6.1.5

  - name: 6.1.[6-9] - Ensure permissions on /etc/passwd- /etc/[g]shadow- /etc/group-
    file:
      path: /etc/{{ item }}
      owner: root
      group: root
      mode: 0000
    with_items:
      - passwd-
      - shadow-
      - group-
      - gshadow-
    tags:
      - 6.1.6
      - 6.1.7
      - 6.1.8
      - 6.1.9
